import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:intl/intl.dart';
import '../models/expense.dart';
import '../models/event.dart';
import '../services/google_sheets_service.dart';
import '../services/services_module.dart';
import '../utils/expense_categories.dart';
import 'edit_expense_screen.dart';
import 'package:url_launcher/url_launcher.dart';

class ExpensesListScreen extends StatefulWidget {
  final GoogleSheetsService sheetsService;
  final String spreadsheetId;

  const ExpensesListScreen({
    super.key,
    required this.sheetsService,
    required this.spreadsheetId,
  });

  @override
  State<ExpensesListScreen> createState() => _ExpensesListScreenState();
}

class _ExpensesListScreenState extends State<ExpensesListScreen> {
  List<Expense> _allExpenses = [];
  List<Expense> _filteredExpenses = [];
  bool _isLoading = false;
  Set<String> _selectedCategories = {};
  bool _selectedOther = false;
  DateTime? _selectedMonth;
  DateTime? _selectedDate;
  DateTime? _startDate;
  DateTime? _endDate;
  String _selectedPaidBy = 'All';
  bool?
  _filterOneTimePurchase; // null = all, true = one-time only, false = recurring only
  String _sortBy = 'date'; // 'date' or 'price'
  bool _sortAscending = false; // false = descending (newest/highest first)
  String _searchQuery = '';
  final TextEditingController _searchController = TextEditingController();
  bool _hasUpdatedCategories = false;

  // Event assignment mode: add/remove expenses from an event
  bool _eventAssignmentMode = false;
  Event? _selectedEvent;
  Set<String> _expenseIdsInEvent = {};
  Set<String> _pendingAdds = {};
  Set<String> _pendingRemoves = {};
  bool _isLoadingEventIds = false;
  bool _isSavingEventAssignments = false;
  final FirebaseDatabaseService _firebaseDb = FirebaseDatabaseService();

  @override
  void initState() {
    super.initState();
    widget.sheetsService.setSpreadsheetId(widget.spreadsheetId);
    _loadExpenses().then((_) {
      // Auto-update categories on first load if needed
      if (!_hasUpdatedCategories && _allExpenses.isNotEmpty) {
        // Check if any expenses need category updates
        final needsUpdate = _allExpenses.any((expense) {
          final newCategory = _mapCategoryToNew(expense.category);
          return newCategory != expense.category;
        });

        if (needsUpdate) {
          _hasUpdatedCategories = true;
          _updateExpenseCategories();
        }
      }
    });
  }

  @override
  void dispose() {
    _searchController.dispose();
    super.dispose();
  }

  Future<void> _loadExpenses() async {
    setState(() => _isLoading = true);
    try {
      final expenses = await widget.sheetsService.getExpenses();
      setState(() {
        _allExpenses = expenses;
        _applyFilters();
      });
    } catch (e) {
      debugPrint('Error loading expenses: $e');
      final errorString = e.toString();

      // Specifically check for 403 Permission Error generated by Google APIs
      if (errorString.contains('403') ||
          errorString.contains('caller does not have permission')) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: const Text(
                'You do not have permission to access this spreadsheet.',
              ),
              backgroundColor: Colors.red,
              duration: const Duration(seconds: 10),
              action: SnackBarAction(
                label: 'Request Access',
                textColor: Colors.white,
                onPressed: () async {
                  final url = Uri.parse(
                    'https://docs.google.com/spreadsheets/d/${widget.spreadsheetId}/edit',
                  );
                  if (await canLaunchUrl(url)) {
                    await launchUrl(url, mode: LaunchMode.externalApplication);
                  } else {
                    if (context.mounted) {
                      ScaffoldMessenger.of(context).showSnackBar(
                        const SnackBar(
                          content: Text(
                            'Could not open browser for requesting access.',
                          ),
                        ),
                      );
                    }
                  }
                },
              ),
            ),
          );
        }
      } else {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('Error loading expenses: $errorString'),
              backgroundColor: Colors.red,
            ),
          );
        }
      }
    } finally {
      setState(() => _isLoading = false);
    }
  }

  String? _mapCategoryToNew(String? oldCategory) {
    if (oldCategory == null || oldCategory.isEmpty) {
      return null;
    }

    final lowerCategory = oldCategory.toLowerCase();

    // Map to new categories based on keywords
    if (lowerCategory.contains('milk')) {
      return 'Milk';
    } else if (lowerCategory.contains('vegetable')) {
      return 'Vegetables';
    } else if (lowerCategory.contains('petrol')) {
      return 'Petrol';
    } else if (lowerCategory.contains('travel') ||
        lowerCategory.contains('cab') ||
        lowerCategory.contains('auto')) {
      return 'Travel Cab Auto';
    } else if (lowerCategory.contains('clothes') ||
        lowerCategory.contains('fashion')) {
      return 'Clothes - Fashion';
    }

    // Return original if no match
    return oldCategory;
  }

  Future<void> _updateExpenseCategories() async {
    setState(() => _isLoading = true);

    try {
      int updatedCount = 0;

      for (var expense in _allExpenses) {
        final newCategory = _mapCategoryToNew(expense.category);

        // Only update if category changed
        if (newCategory != expense.category) {
          final updatedExpense = Expense(
            id: expense.id,
            label: expense.label,
            price: expense.price,
            category: newCategory,
            note: expense.note,
            expenseDate: expense.expenseDate,
            timestamp: expense.timestamp,
            paidBy: expense.paidBy,
            isOneTimePurchase: expense.isOneTimePurchase,
            addedByEmail: expense.addedByEmail,
          );

          await widget.sheetsService.updateExpense(updatedExpense);
          updatedCount++;
        }
      }

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(
              'Updated $updatedCount expense(s) with new categories',
            ),
            backgroundColor: Colors.green,
            duration: const Duration(seconds: 3),
          ),
        );
      }

      // Reload expenses to reflect changes
      await _loadExpenses();
    } catch (e) {
      debugPrint('Error updating expense categories: $e');
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error updating categories: ${e.toString()}'),
            backgroundColor: Colors.red,
            duration: const Duration(seconds: 5),
          ),
        );
      }
    } finally {
      setState(() => _isLoading = false);
    }
  }

  void _applyFilters() {
    var filtered = List<Expense>.from(_allExpenses);

    // Category filter - support multiple categories
    if (_selectedCategories.isNotEmpty || _selectedOther) {
      filtered = filtered.where((e) {
        // Check for "Other" category
        if (_selectedOther) {
          final isOther =
              e.category == null ||
              e.category!.isEmpty ||
              !ExpenseCategories.categories.any(
                (cat) => e.category!.toLowerCase().contains(cat.toLowerCase()),
              );
          if (isOther) return true;
        }

        // Check for selected categories
        if (_selectedCategories.isNotEmpty &&
            e.category != null &&
            e.category!.isNotEmpty) {
          // Split category string (may contain multiple categories separated by comma)
          final expenseCategories = e.category!
              .split(',')
              .map((c) => c.trim().toLowerCase())
              .toSet();

          // Check if any selected category matches any expense category
          return _selectedCategories.any((selectedCat) {
            final lowerSelected = selectedCat.toLowerCase();
            return expenseCategories.any(
              (expCat) =>
                  expCat.contains(lowerSelected) ||
                  lowerSelected.contains(expCat),
            );
          });
        }

        return false;
      }).toList();
    }

    // Paid By filter
    if (_selectedPaidBy != 'All') {
      filtered = filtered.where((e) {
        if (_selectedPaidBy == 'Not Specified') {
          return e.paidBy == null || e.paidBy!.isEmpty;
        }
        return e.paidBy == _selectedPaidBy;
      }).toList();
    }

    // Month filter
    if (_selectedMonth != null) {
      filtered = filtered.where((e) {
        return e.expenseDate.year == _selectedMonth!.year &&
            e.expenseDate.month == _selectedMonth!.month;
      }).toList();
    }

    // Date filter
    if (_selectedDate != null) {
      filtered = filtered.where((e) {
        return e.expenseDate.year == _selectedDate!.year &&
            e.expenseDate.month == _selectedDate!.month &&
            e.expenseDate.day == _selectedDate!.day;
      }).toList();
    }

    // Date range filter
    if (_startDate != null || _endDate != null) {
      filtered = filtered.where((e) {
        if (_startDate != null && e.expenseDate.isBefore(_startDate!)) {
          return false;
        }
        if (_endDate != null) {
          final endDateEndOfDay = DateTime(
            _endDate!.year,
            _endDate!.month,
            _endDate!.day,
            23,
            59,
            59,
          );
          if (e.expenseDate.isAfter(endDateEndOfDay)) {
            return false;
          }
        }
        return true;
      }).toList();
    }

    // One Time Purchase filter
    if (_filterOneTimePurchase != null) {
      filtered = filtered.where((e) {
        return e.isOneTimePurchase == _filterOneTimePurchase;
      }).toList();
    }

    // Search filter
    if (_searchQuery.isNotEmpty) {
      final searchWords = _searchQuery
          .toLowerCase()
          .trim()
          .split(' ')
          .where((word) => word.isNotEmpty)
          .toList();
      filtered = filtered.where((e) {
        final label = e.label.toLowerCase();
        final note = (e.note ?? '').toLowerCase();
        final searchText = '$label $note';

        // All search words must be found in label or note
        return searchWords.every((word) => searchText.contains(word));
      }).toList();
    }

    // Sort
    if (_sortBy == 'price') {
      filtered.sort((a, b) {
        final comparison = a.price.compareTo(b.price);
        return _sortAscending ? comparison : -comparison;
      });
    } else {
      // Sort by date (default)
      filtered.sort((a, b) {
        final comparison = a.expenseDate.compareTo(b.expenseDate);
        return _sortAscending ? comparison : -comparison;
      });
    }

    setState(() {
      _filteredExpenses = filtered;
    });
  }

  Future<void> _selectMonth() async {
    final now = DateTime.now();
    final currentYear = _selectedMonth?.year ?? now.year;
    final currentMonth = _selectedMonth?.month ?? now.month;

    int? selectedYear = currentYear;
    int? selectedMonth = currentMonth;

    final result = await showDialog<Map<String, int>>(
      context: context,
      builder: (context) {
        return StatefulBuilder(
          builder: (context, setDialogState) {
            return AlertDialog(
              title: const Text('Select Month & Year'),
              content: SizedBox(
                width: double.maxFinite,
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    // Year selector
                    Row(
                      children: [
                        const Text('Year: '),
                        Expanded(
                          child: DropdownButton<int>(
                            value: selectedYear,
                            isExpanded: true,
                            items:
                                List.generate(
                                  now.year - 1999,
                                  (index) => now.year - index,
                                ).map((year) {
                                  return DropdownMenuItem(
                                    value: year,
                                    child: Text(year.toString()),
                                  );
                                }).toList(),
                            onChanged: (value) {
                              setDialogState(() {
                                selectedYear = value;
                              });
                            },
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 16),
                    // Month grid
                    GridView.builder(
                      shrinkWrap: true,
                      physics: const NeverScrollableScrollPhysics(),
                      gridDelegate:
                          const SliverGridDelegateWithFixedCrossAxisCount(
                            crossAxisCount: 3,
                            childAspectRatio: 2.5,
                            crossAxisSpacing: 8,
                            mainAxisSpacing: 8,
                          ),
                      itemCount: 12,
                      itemBuilder: (context, index) {
                        final month = index + 1;
                        final isSelected = selectedMonth == month;
                        return InkWell(
                          onTap: () {
                            setDialogState(() {
                              selectedMonth = month;
                            });
                          },
                          child: Container(
                            decoration: BoxDecoration(
                              color: isSelected
                                  ? Theme.of(context).colorScheme.primary
                                  : Colors.grey[200],
                              borderRadius: BorderRadius.circular(4),
                            ),
                            alignment: Alignment.center,
                            child: Text(
                              DateFormat('MMM').format(DateTime(2000, month)),
                              style: TextStyle(
                                color: isSelected ? Colors.white : Colors.black,
                                fontWeight: isSelected
                                    ? FontWeight.bold
                                    : FontWeight.normal,
                                fontSize: 12,
                              ),
                            ),
                          ),
                        );
                      },
                    ),
                  ],
                ),
              ),
              actions: [
                TextButton(
                  onPressed: () => Navigator.pop(context),
                  child: const Text('Cancel'),
                ),
                ElevatedButton(
                  onPressed: () {
                    if (selectedYear != null && selectedMonth != null) {
                      Navigator.pop(context, {
                        'year': selectedYear!,
                        'month': selectedMonth!,
                      });
                    }
                  },
                  child: const Text('Select'),
                ),
              ],
            );
          },
        );
      },
    );

    if (result != null) {
      setState(() {
        _selectedMonth = DateTime(result['year']!, result['month']!);
        _selectedDate = null; // Clear date filter when month is selected
      });
      _applyFilters();
    }
  }

  Future<void> _selectDate() async {
    final DateTime? picked = await showDatePicker(
      context: context,
      initialDate: _selectedDate ?? DateTime.now(),
      firstDate: DateTime(2000),
      lastDate: DateTime.now(),
    );
    if (picked != null) {
      setState(() {
        _selectedDate = picked;
        _selectedMonth = null; // Clear month filter when date is selected
      });
      _applyFilters();
    }
  }

  Future<void> _selectDateRange() async {
    final DateTime now = DateTime.now();
    DateTime? startDate = _startDate ?? DateTime(now.year, now.month - 1, 1);
    DateTime? endDate = _endDate ?? now;

    final result = await showDialog<Map<String, DateTime?>>(
      context: context,
      builder: (context) {
        return StatefulBuilder(
          builder: (context, setDialogState) {
            return AlertDialog(
              title: const Text('Select Date Range'),
              content: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  Row(
                    children: [
                      const Text('Start Date: '),
                      Expanded(
                        child: OutlinedButton(
                          onPressed: () async {
                            final picked = await showDatePicker(
                              context: context,
                              initialDate: startDate ?? DateTime.now(),
                              firstDate: DateTime(2000),
                              lastDate: endDate ?? DateTime.now(),
                            );
                            if (picked != null) {
                              setDialogState(() {
                                startDate = picked;
                              });
                            }
                          },
                          child: Text(
                            startDate != null
                                ? DateFormat('MMM dd, yyyy').format(startDate!)
                                : 'Select',
                          ),
                        ),
                      ),
                    ],
                  ),
                  const SizedBox(height: 16),
                  Row(
                    children: [
                      const Text('End Date: '),
                      Expanded(
                        child: OutlinedButton(
                          onPressed: () async {
                            final picked = await showDatePicker(
                              context: context,
                              initialDate: endDate ?? DateTime.now(),
                              firstDate: startDate ?? DateTime(2000),
                              lastDate: DateTime.now(),
                            );
                            if (picked != null) {
                              setDialogState(() {
                                endDate = picked;
                              });
                            }
                          },
                          child: Text(
                            endDate != null
                                ? DateFormat('MMM dd, yyyy').format(endDate!)
                                : 'Select',
                          ),
                        ),
                      ),
                    ],
                  ),
                ],
              ),
              actions: [
                TextButton(
                  onPressed: () => Navigator.pop(context),
                  child: const Text('Cancel'),
                ),
                TextButton(
                  onPressed: () {
                    setDialogState(() {
                      startDate = null;
                      endDate = null;
                    });
                  },
                  child: const Text('Clear'),
                ),
                ElevatedButton(
                  onPressed: () {
                    Navigator.pop(context, {
                      'startDate': startDate,
                      'endDate': endDate,
                    });
                  },
                  child: const Text('Apply'),
                ),
              ],
            );
          },
        );
      },
    );

    if (result != null) {
      setState(() {
        _startDate = result['startDate'];
        _endDate = result['endDate'];
        _selectedMonth = null; // Clear month filter when date range is selected
        _selectedDate = null; // Clear date filter when date range is selected
      });
      _applyFilters();
    }
  }

  void _clearFilters() {
    setState(() {
      _selectedCategories.clear();
      _selectedOther = false;
      _selectedMonth = null;
      _selectedDate = null;
      _startDate = null;
      _endDate = null;
      _selectedPaidBy = 'All';
      _filterOneTimePurchase = null;
      _sortBy = 'date';
      _sortAscending = false;
      _searchQuery = '';
      _searchController.clear();
    });
    _applyFilters();
  }

  void _onSearchChanged(String query) {
    setState(() {
      _searchQuery = query;
    });
    _applyFilters();
  }

  List<String> _getPaidByOptions() {
    final paidBySet = <String>{};
    for (var expense in _allExpenses) {
      if (expense.paidBy != null && expense.paidBy!.isNotEmpty) {
        paidBySet.add(expense.paidBy!);
      }
    }
    final options = ['All', ...paidBySet.toList()..sort()];
    if (_allExpenses.any((e) => e.paidBy == null || e.paidBy!.isEmpty)) {
      options.add('Not Specified');
    }
    return options;
  }

  double _getTotalAmount() {
    if (_eventAssignmentMode && _selectedEvent != null) {
      return _filteredExpenses
          .where((e) => _isExpenseInEvent(e.id))
          .fold(0.0, (sum, expense) => sum + expense.price);
    }
    return _filteredExpenses.fold(0.0, (sum, expense) => sum + expense.price);
  }

  bool _isExpenseInEvent(String expenseId) {
    final inBase = _expenseIdsInEvent.contains(expenseId);
    final added = _pendingAdds.contains(expenseId);
    final removed = _pendingRemoves.contains(expenseId);
    return (inBase || added) && !removed;
  }

  void _onAddExpenseToEvent(String expenseId) {
    setState(() {
      _pendingRemoves.remove(expenseId);
      _pendingAdds.add(expenseId);
    });
  }

  void _onRemoveExpenseFromEvent(String expenseId) {
    setState(() {
      _pendingAdds.remove(expenseId);
      _pendingRemoves.add(expenseId);
    });
  }

  Future<void> _openEventListDialog() async {
    final spreadsheetId = widget.spreadsheetId;
    if (spreadsheetId.isEmpty) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('No spreadsheet ID'),
            backgroundColor: Colors.orange,
          ),
        );
      }
      return;
    }
    List<Event> events;
    try {
      events = await _firebaseDb.getEvents(spreadsheetId);
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error loading events: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
      return;
    }
    if (!mounted) return;
    if (events.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('No events yet. Create events first.'),
          backgroundColor: Colors.orange,
        ),
      );
      return;
    }
    final chosen = await showDialog<Event>(
      context: context,
      builder: (ctx) => AlertDialog(
        title: const Text('Select Event'),
        content: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: events
                .map(
                  (e) => ListTile(
                    title: Text(e.name),
                    onTap: () => Navigator.pop(ctx, e),
                  ),
                )
                .toList(),
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx),
            child: const Text('Cancel'),
          ),
        ],
      ),
    );
    if (chosen != null) {
      setState(() {
        _selectedEvent = chosen;
        _eventAssignmentMode = true;
        _pendingAdds.clear();
        _pendingRemoves.clear();
      });
      _loadExpenseIdsForSelectedEvent();
    }
  }

  Future<void> _loadExpenseIdsForSelectedEvent() async {
    final spreadsheetId = widget.spreadsheetId;
    final event = _selectedEvent;
    if (spreadsheetId.isEmpty || event == null) return;
    setState(() => _isLoadingEventIds = true);
    try {
      final ids = await _firebaseDb.getExpenseIdsForEvent(
        spreadsheetId,
        event.id,
      );
      if (mounted) {
        setState(() {
          _expenseIdsInEvent = ids.toSet();
          _isLoadingEventIds = false;
        });
      }
    } catch (e) {
      if (mounted) {
        setState(() => _isLoadingEventIds = false);
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error loading event expenses: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    }
  }

  void _exitEventAssignmentMode() {
    setState(() {
      _eventAssignmentMode = false;
      _selectedEvent = null;
      _expenseIdsInEvent = {};
      _pendingAdds = {};
      _pendingRemoves = {};
    });
  }

  Future<void> _saveEventAssignments() async {
    final spreadsheetId = widget.spreadsheetId;
    final event = _selectedEvent;
    if (spreadsheetId.isEmpty || event == null) return;
    final toAdd = _pendingAdds.toList();
    final toRemove = _pendingRemoves.toList();
    if (toAdd.isEmpty && toRemove.isEmpty) {
      if (mounted) {
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(const SnackBar(content: Text('No changes to save')));
      }
      return;
    }
    setState(() => _isSavingEventAssignments = true);
    try {
      for (final expenseId in toAdd) {
        final current = await _firebaseDb.getEventIdsForExpense(
          spreadsheetId,
          expenseId,
        );
        final updated = [...current, event.id].toSet().toList();
        await _firebaseDb.setExpenseEvents(spreadsheetId, expenseId, updated);
      }
      for (final expenseId in toRemove) {
        final current = await _firebaseDb.getEventIdsForExpense(
          spreadsheetId,
          expenseId,
        );
        final updated = current.where((id) => id != event.id).toList();
        await _firebaseDb.setExpenseEvents(spreadsheetId, expenseId, updated);
      }
      if (mounted) {
        setState(() {
          _pendingAdds.clear();
          _pendingRemoves.clear();
          _isSavingEventAssignments = false;
        });
        _loadExpenseIdsForSelectedEvent();
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Event assignments updated'),
            backgroundColor: Colors.green,
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        setState(() => _isSavingEventAssignments = false);
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error saving: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        leading: IconButton(
          icon: const Icon(Icons.arrow_back),
          onPressed: () => Navigator.pop(context),
          padding: EdgeInsets.zero,
          constraints: const BoxConstraints(),
        ),
        leadingWidth: 40,
        automaticallyImplyLeading: false,
        title: TextField(
          controller: _searchController,
          decoration: InputDecoration(
            hintText: 'Search by label or notes...',
            hintStyle: const TextStyle(color: Colors.grey),
            prefixIcon: const Icon(Icons.search, color: Colors.black),
            suffixIcon: _searchQuery.isNotEmpty
                ? IconButton(
                    icon: const Icon(Icons.clear, color: Colors.black),
                    onPressed: () {
                      _searchController.clear();
                      _onSearchChanged('');
                    },
                  )
                : null,
            border: InputBorder.none,
            enabledBorder: InputBorder.none,
            focusedBorder: InputBorder.none,
            contentPadding: const EdgeInsets.symmetric(
              horizontal: 16,
              vertical: 12,
            ),
          ),
          style: const TextStyle(color: Colors.black),
          onChanged: _onSearchChanged,
        ),
        actions: [
          IconButton(
            icon: const Icon(Icons.event),
            onPressed: _openEventListDialog,
            tooltip: 'Add expenses to event',
          ),
          if (_eventAssignmentMode)
            IconButton(
              icon: const Icon(Icons.close),
              onPressed: _exitEventAssignmentMode,
              tooltip: 'Exit event mode',
            ),
          IconButton(
            icon: const Icon(Icons.refresh),
            onPressed: _loadExpenses,
            tooltip: 'Refresh',
          ),
        ],
      ),
      body: Column(
        children: [
          // Filters Section
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
            color: Colors.grey[100],
            child: Column(
              children: [
                // Category Filter - Chips (Multiple Selection)
                SizedBox(
                  height: 32,
                  child: ListView(
                    scrollDirection: Axis.horizontal,
                    children: [
                      FilterChip(
                        label: const Text(
                          'All',
                          style: TextStyle(color: Colors.black, fontSize: 11),
                        ),
                        selected:
                            _selectedCategories.isEmpty && !_selectedOther,
                        onSelected: (selected) {
                          setState(() {
                            if (selected) {
                              _selectedCategories.clear();
                              _selectedOther = false;
                            }
                          });
                          _applyFilters();
                        },
                        padding: const EdgeInsets.symmetric(horizontal: 4),
                        materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
                        visualDensity: VisualDensity.compact,
                      ),
                      const SizedBox(width: 4),
                      ...ExpenseCategories.categories.map((category) {
                        return Padding(
                          padding: const EdgeInsets.only(right: 4),
                          child: FilterChip(
                            label: Text(
                              category,
                              style: const TextStyle(
                                color: Colors.black,
                                fontSize: 11,
                              ),
                            ),
                            selected: _selectedCategories.contains(category),
                            onSelected: (selected) {
                              setState(() {
                                if (selected) {
                                  _selectedCategories.add(category);
                                } else {
                                  _selectedCategories.remove(category);
                                }
                              });
                              _applyFilters();
                            },
                            padding: const EdgeInsets.symmetric(horizontal: 4),
                            materialTapTargetSize:
                                MaterialTapTargetSize.shrinkWrap,
                            visualDensity: VisualDensity.compact,
                          ),
                        );
                      }),
                      const SizedBox(width: 4),
                      FilterChip(
                        label: const Text(
                          'Other',
                          style: TextStyle(color: Colors.black, fontSize: 11),
                        ),
                        selected: _selectedOther,
                        onSelected: (selected) {
                          setState(() {
                            _selectedOther = selected;
                          });
                          _applyFilters();
                        },
                        padding: const EdgeInsets.symmetric(horizontal: 4),
                        materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
                        visualDensity: VisualDensity.compact,
                      ),
                    ],
                  ),
                ),
                const SizedBox(height: 8),
                // Scrollable Filters Row
                SizedBox(
                  height: 32,
                  child: Row(
                    children: [
                      Expanded(
                        child: ListView(
                          scrollDirection: Axis.horizontal,
                          children: [
                            OutlinedButton.icon(
                              style: ButtonStyle(
                                padding: MaterialStateProperty.all(
                                  const EdgeInsets.symmetric(
                                    horizontal: 8,
                                    vertical: 4,
                                  ),
                                ),
                                foregroundColor: MaterialStateProperty.all(
                                  Colors.black,
                                ),
                                minimumSize: MaterialStateProperty.all(
                                  const Size(0, 32),
                                ),
                                tapTargetSize: MaterialTapTargetSize.shrinkWrap,
                              ),
                              onPressed: _selectMonth,
                              icon: const Icon(
                                Icons.calendar_month,
                                color: Colors.black,
                                size: 16,
                              ),
                              label: Text(
                                _selectedMonth != null
                                    ? DateFormat(
                                        'MMM yyyy',
                                      ).format(_selectedMonth!)
                                    : 'Month',
                                style: const TextStyle(
                                  color: Colors.black,
                                  fontSize: 12,
                                ),
                              ),
                            ),
                            const SizedBox(width: 4),
                            OutlinedButton.icon(
                              style: ButtonStyle(
                                padding: MaterialStateProperty.all(
                                  const EdgeInsets.symmetric(
                                    horizontal: 8,
                                    vertical: 4,
                                  ),
                                ),
                                foregroundColor: MaterialStateProperty.all(
                                  Colors.black,
                                ),
                                minimumSize: MaterialStateProperty.all(
                                  const Size(0, 32),
                                ),
                                tapTargetSize: MaterialTapTargetSize.shrinkWrap,
                              ),
                              onPressed: _selectDate,
                              icon: const Icon(
                                Icons.calendar_today,
                                color: Colors.black,
                                size: 16,
                              ),
                              label: Text(
                                _selectedDate != null
                                    ? DateFormat(
                                        'MMM dd, yyyy',
                                      ).format(_selectedDate!)
                                    : 'Date',
                                style: const TextStyle(
                                  color: Colors.black,
                                  fontSize: 12,
                                ),
                              ),
                            ),
                            const SizedBox(width: 4),
                            OutlinedButton.icon(
                              style: ButtonStyle(
                                padding: MaterialStateProperty.all(
                                  const EdgeInsets.symmetric(
                                    horizontal: 8,
                                    vertical: 4,
                                  ),
                                ),
                                foregroundColor: MaterialStateProperty.all(
                                  Colors.black,
                                ),
                                minimumSize: MaterialStateProperty.all(
                                  const Size(0, 32),
                                ),
                                tapTargetSize: MaterialTapTargetSize.shrinkWrap,
                              ),
                              onPressed: _selectDateRange,
                              icon: const Icon(
                                Icons.date_range,
                                color: Colors.black,
                                size: 16,
                              ),
                              label: Text(
                                _startDate != null || _endDate != null
                                    ? '${_startDate != null ? DateFormat('MMM dd').format(_startDate!) : 'Start'} - ${_endDate != null ? DateFormat('MMM dd').format(_endDate!) : 'End'}'
                                    : 'Date Range',
                                style: const TextStyle(
                                  color: Colors.black,
                                  fontSize: 12,
                                ),
                              ),
                            ),
                            const SizedBox(width: 4),
                            PopupMenuButton<String>(
                              child: Container(
                                padding: const EdgeInsets.symmetric(
                                  horizontal: 8,
                                  vertical: 4,
                                ),
                                decoration: BoxDecoration(
                                  border: Border.all(color: Colors.grey),
                                  borderRadius: BorderRadius.circular(4),
                                ),
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  children: [
                                    const Icon(
                                      Icons.person,
                                      color: Colors.black,
                                      size: 16,
                                    ),
                                    const SizedBox(width: 4),
                                    Flexible(
                                      child: Text(
                                        _selectedPaidBy,
                                        style: const TextStyle(
                                          color: Colors.black,
                                          fontSize: 12,
                                        ),
                                        overflow: TextOverflow.ellipsis,
                                      ),
                                    ),
                                    const Icon(
                                      Icons.arrow_drop_down,
                                      color: Colors.black,
                                      size: 16,
                                    ),
                                  ],
                                ),
                              ),
                              itemBuilder: (context) {
                                return _getPaidByOptions().map((option) {
                                  return PopupMenuItem<String>(
                                    value: option,
                                    child: Text(option),
                                  );
                                }).toList();
                              },
                              onSelected: (value) {
                                setState(() {
                                  _selectedPaidBy = value;
                                });
                                _applyFilters();
                              },
                            ),
                            const SizedBox(width: 4),
                            PopupMenuButton<String>(
                              child: Container(
                                padding: const EdgeInsets.symmetric(
                                  horizontal: 8,
                                  vertical: 4,
                                ),
                                decoration: BoxDecoration(
                                  border: Border.all(color: Colors.grey),
                                  borderRadius: BorderRadius.circular(4),
                                ),
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  children: [
                                    const Icon(
                                      Icons.shopping_cart,
                                      color: Colors.black,
                                      size: 16,
                                    ),
                                    const SizedBox(width: 4),
                                    Flexible(
                                      child: Text(
                                        _filterOneTimePurchase == null
                                            ? 'All'
                                            : _filterOneTimePurchase == true
                                            ? 'One-Time'
                                            : 'Recurring',
                                        style: const TextStyle(
                                          color: Colors.black,
                                          fontSize: 12,
                                        ),
                                        overflow: TextOverflow.ellipsis,
                                      ),
                                    ),
                                    const Icon(
                                      Icons.arrow_drop_down,
                                      color: Colors.black,
                                      size: 16,
                                    ),
                                  ],
                                ),
                              ),
                              itemBuilder: (context) {
                                return [
                                  const PopupMenuItem(
                                    value: 'all',
                                    child: Text('All'),
                                  ),
                                  const PopupMenuItem(
                                    value: 'oneTime',
                                    child: Text('One-Time Only'),
                                  ),
                                  const PopupMenuItem(
                                    value: 'recurring',
                                    child: Text('Recurring Only'),
                                  ),
                                ];
                              },
                              onSelected: (value) {
                                setState(() {
                                  if (value == 'all') {
                                    _filterOneTimePurchase = null;
                                  } else if (value == 'oneTime') {
                                    _filterOneTimePurchase = true;
                                  } else {
                                    _filterOneTimePurchase = false;
                                  }
                                });
                                _applyFilters();
                              },
                            ),
                            const SizedBox(width: 4),
                            PopupMenuButton<String>(
                              child: Container(
                                padding: const EdgeInsets.symmetric(
                                  horizontal: 8,
                                  vertical: 4,
                                ),
                                decoration: BoxDecoration(
                                  border: Border.all(color: Colors.grey),
                                  borderRadius: BorderRadius.circular(4),
                                ),
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  children: [
                                    Icon(
                                      _sortBy == 'price'
                                          ? Icons.attach_money
                                          : Icons.calendar_today,
                                      color: Colors.black,
                                      size: 16,
                                    ),
                                    const SizedBox(width: 4),
                                    Flexible(
                                      child: Text(
                                        _sortBy == 'price'
                                            ? (_sortAscending
                                                  ? 'Price ↑'
                                                  : 'Price ↓')
                                            : (_sortAscending
                                                  ? 'Date ↑'
                                                  : 'Date ↓'),
                                        style: const TextStyle(
                                          color: Colors.black,
                                          fontSize: 12,
                                        ),
                                        overflow: TextOverflow.ellipsis,
                                      ),
                                    ),
                                    const Icon(
                                      Icons.arrow_drop_down,
                                      color: Colors.black,
                                      size: 16,
                                    ),
                                  ],
                                ),
                              ),
                              itemBuilder: (context) {
                                return [
                                  const PopupMenuItem(
                                    value: 'date_desc',
                                    child: Text('Date (Newest First)'),
                                  ),
                                  const PopupMenuItem(
                                    value: 'date_asc',
                                    child: Text('Date (Oldest First)'),
                                  ),
                                  const PopupMenuItem(
                                    value: 'price_desc',
                                    child: Text('Price (Highest First)'),
                                  ),
                                  const PopupMenuItem(
                                    value: 'price_asc',
                                    child: Text('Price (Lowest First)'),
                                  ),
                                ];
                              },
                              onSelected: (value) {
                                setState(() {
                                  if (value == 'date_desc') {
                                    _sortBy = 'date';
                                    _sortAscending = false;
                                  } else if (value == 'date_asc') {
                                    _sortBy = 'date';
                                    _sortAscending = true;
                                  } else if (value == 'price_desc') {
                                    _sortBy = 'price';
                                    _sortAscending = false;
                                  } else if (value == 'price_asc') {
                                    _sortBy = 'price';
                                    _sortAscending = true;
                                  }
                                });
                                _applyFilters();
                              },
                            ),
                          ],
                        ),
                      ),
                      // Fixed Clear Button
                      InkWell(
                        onTap: _clearFilters,
                        child: Container(
                          padding: const EdgeInsets.all(4),
                          child: const Icon(Icons.clear, size: 18),
                        ),
                      ),
                    ],
                  ),
                ),
                // Total Amount
                if (_filteredExpenses.isNotEmpty)
                  Padding(
                    padding: const EdgeInsets.only(top: 12),
                    child: Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        const Text(
                          'Total:',
                          style: TextStyle(
                            fontSize: 18,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                        Text(
                          '₹${_getTotalAmount().toStringAsFixed(0)}',
                          style: TextStyle(
                            fontSize: 20,
                            fontWeight: FontWeight.bold,
                            color: Theme.of(context).colorScheme.primary,
                          ),
                        ),
                      ],
                    ),
                  ),
              ],
            ),
          ),
          // Event mode banner
          if (_eventAssignmentMode && _selectedEvent != null)
            Container(
              width: double.infinity,
              padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
              color: Theme.of(context).colorScheme.primaryContainer,
              child: Row(
                children: [
                  Icon(
                    Icons.event,
                    size: 20,
                    color: Theme.of(context).colorScheme.onPrimaryContainer,
                  ),
                  const SizedBox(width: 8),
                  Expanded(
                    child: Text(
                      'Event: ${_selectedEvent!.name} — tap +/− next to price',
                      style: TextStyle(
                        fontSize: 12,
                        color: Theme.of(context).colorScheme.onPrimaryContainer,
                      ),
                    ),
                  ),
                  if (_isLoadingEventIds)
                    const SizedBox(
                      width: 16,
                      height: 16,
                      child: CircularProgressIndicator(strokeWidth: 2),
                    ),
                ],
              ),
            ),
          // Expenses List
          Expanded(
            child: _isLoading
                ? const Center(child: CircularProgressIndicator())
                : _filteredExpenses.isEmpty
                ? Center(
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Icon(
                          Icons.receipt_long,
                          size: 64,
                          color: Colors.grey[400],
                        ),
                        const SizedBox(height: 16),
                        Text(
                          _allExpenses.isEmpty
                              ? 'No expenses yet'
                              : 'No expenses match your filters',
                          style: TextStyle(
                            fontSize: 16,
                            color: Colors.grey[600],
                          ),
                        ),
                      ],
                    ),
                  )
                : RefreshIndicator(
                    onRefresh: _loadExpenses,
                    child: ListView.builder(
                      itemCount: _filteredExpenses.length,
                      padding: EdgeInsets.only(
                        left: 8,
                        right: 8,
                        top: 8,
                        bottom: _eventAssignmentMode ? 72 : 8,
                      ),
                      itemBuilder: (context, index) {
                        final expense = _filteredExpenses[index];
                        return _ExpenseCard(
                          expense: expense,
                          onEdit: () => _editExpense(expense),
                          onDelete: () => _deleteExpense(expense),
                          isSearching: _searchQuery.isNotEmpty,
                          eventAssignmentMode: _eventAssignmentMode,
                          isInEvent: _isExpenseInEvent(expense.id),
                          onAddToEvent: () => _onAddExpenseToEvent(expense.id),
                          onRemoveFromEvent: () =>
                              _onRemoveExpenseFromEvent(expense.id),
                        );
                      },
                    ),
                  ),
          ),
          // Update button when in event mode
          if (_eventAssignmentMode && _selectedEvent != null)
            SafeArea(
              child: Padding(
                padding: const EdgeInsets.all(12),
                child: SizedBox(
                  width: double.infinity,
                  child: ElevatedButton.icon(
                    onPressed:
                        (_pendingAdds.isEmpty && _pendingRemoves.isEmpty) ||
                            _isSavingEventAssignments
                        ? null
                        : _saveEventAssignments,
                    icon: _isSavingEventAssignments
                        ? const SizedBox(
                            width: 20,
                            height: 20,
                            child: CircularProgressIndicator(strokeWidth: 2),
                          )
                        : const Icon(Icons.save),
                    label: Text(
                      _isSavingEventAssignments
                          ? 'Saving...'
                          : 'Update event assignments',
                    ),
                  ),
                ),
              ),
            ),
        ],
      ),
    );
  }

  Future<void> _editExpense(Expense expense) async {
    final result = await Navigator.push(
      context,
      MaterialPageRoute(
        builder: (context) => EditExpenseScreen(
          expense: expense,
          sheetsService: widget.sheetsService,
          spreadsheetId: widget.spreadsheetId,
        ),
      ),
    );

    if (result == true) {
      _loadExpenses();
    }
  }

  Future<void> _deleteExpense(Expense expense) async {
    final confirm = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        title: Row(
          children: [
            Icon(Icons.warning, color: Colors.orange[700], size: 28),
            const SizedBox(width: 8),
            const Expanded(
              child: Text(
                'Delete Expense',
                style: TextStyle(fontWeight: FontWeight.bold),
              ),
            ),
          ],
        ),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text(
              'Are you sure you want to delete this expense?',
              style: TextStyle(fontSize: 16),
            ),
            const SizedBox(height: 12),
            Container(
              padding: const EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: Colors.grey[100],
                borderRadius: BorderRadius.circular(8),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'Label: ${expense.label}',
                    style: const TextStyle(fontWeight: FontWeight.bold),
                  ),
                  const SizedBox(height: 4),
                  Text('Amount: ₹${expense.price.toStringAsFixed(0)}'),
                  if (expense.category != null)
                    Text('Category: ${expense.category}'),
                ],
              ),
            ),
            const SizedBox(height: 8),
            Text(
              'This action cannot be undone.',
              style: TextStyle(
                color: Colors.red[700],
                fontSize: 12,
                fontStyle: FontStyle.italic,
              ),
            ),
          ],
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context, false),
            child: const Text('No, Cancel', style: TextStyle(fontSize: 16)),
          ),
          ElevatedButton(
            onPressed: () => Navigator.pop(context, true),
            style: ElevatedButton.styleFrom(
              backgroundColor: Colors.red,
              foregroundColor: Colors.white,
              padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
            ),
            child: const Text(
              'Yes, Delete',
              style: TextStyle(fontSize: 16, fontWeight: FontWeight.bold),
            ),
          ),
        ],
      ),
    );

    if (confirm == true) {
      setState(() => _isLoading = true);
      try {
        await widget.sheetsService.deleteExpense(expense.id);
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('Expense deleted successfully'),
              backgroundColor: Colors.green,
            ),
          );
        }
        _loadExpenses();
      } catch (e) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text('Error deleting expense: ${e.toString()}'),
              backgroundColor: Colors.red,
            ),
          );
        }
      } finally {
        setState(() => _isLoading = false);
      }
    }
  }
}

class _ExpenseCard extends StatelessWidget {
  final Expense expense;
  final VoidCallback onEdit;
  final VoidCallback onDelete;
  final bool isSearching;
  final bool eventAssignmentMode;
  final bool isInEvent;
  final VoidCallback? onAddToEvent;
  final VoidCallback? onRemoveFromEvent;

  const _ExpenseCard({
    required this.expense,
    required this.onEdit,
    required this.onDelete,
    required this.isSearching,
    this.eventAssignmentMode = false,
    this.isInEvent = false,
    this.onAddToEvent,
    this.onRemoveFromEvent,
  });

  void _showDetailsDialog(BuildContext context) {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: Text(
          expense.label,
          style: const TextStyle(fontWeight: FontWeight.bold),
        ),
        content: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              _buildDetailRow('Amount', '₹${expense.price.toStringAsFixed(0)}'),
              if (expense.category != null && expense.category!.isNotEmpty)
                _buildDetailRow('Category', expense.category!),
              if (expense.paidBy != null && expense.paidBy!.isNotEmpty)
                _buildDetailRow('Paid By', expense.paidBy!),
              _buildDetailRow(
                'Date',
                DateFormat('MMM dd, yyyy').format(expense.expenseDate),
              ),
              if (expense.note != null && expense.note!.isNotEmpty) ...[
                const SizedBox(height: 12),
                const Text(
                  'Notes:',
                  style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14),
                ),
                const SizedBox(height: 4),
                Container(
                  width: double.infinity,
                  padding: const EdgeInsets.all(12),
                  decoration: BoxDecoration(
                    color: Colors.grey[100],
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: Text(
                    expense.note!,
                    style: const TextStyle(fontSize: 14),
                  ),
                ),
              ],
            ],
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Close'),
          ),
        ],
      ),
    );
  }

  Widget _buildDetailRow(String label, String value) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          SizedBox(
            width: 80,
            child: Text(
              '$label:',
              style: const TextStyle(fontWeight: FontWeight.w500, fontSize: 14),
            ),
          ),
          Expanded(child: Text(value, style: const TextStyle(fontSize: 14))),
        ],
      ),
    );
  }

  void _showActionDialog(BuildContext context) {
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: Text(expense.label),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text('Amount: ₹${expense.price.toStringAsFixed(0)}'),
            if (expense.category != null && expense.category!.isNotEmpty)
              Padding(
                padding: const EdgeInsets.only(top: 4),
                child: Text('Category: ${expense.category}'),
              ),
          ],
        ),
        actions: [
          TextButton(
            onPressed: () {
              Navigator.pop(context);
              onEdit();
            },
            child: const Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                Icon(Icons.edit, size: 18),
                SizedBox(width: 4),
                Text('Edit'),
              ],
            ),
          ),
          ElevatedButton(
            onPressed: () {
              Navigator.pop(context);
              onDelete();
            },
            style: ElevatedButton.styleFrom(
              backgroundColor: Colors.red,
              foregroundColor: Colors.white,
            ),
            child: const Row(
              mainAxisSize: MainAxisSize.min,
              children: [
                Icon(Icons.delete, size: 18),
                SizedBox(width: 4),
                Text('Delete'),
              ],
            ),
          ),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => _showDetailsDialog(context),
      onLongPress: () => _showActionDialog(context),
      onDoubleTap: () => _showActionDialog(context),
      child: Card(
        margin: const EdgeInsets.symmetric(vertical: 2, horizontal: 8),
        elevation: 1,
        child: Padding(
          padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
          child: Row(
            children: [
              // Category Icon
              Container(
                width: 40,
                height: 40,
                decoration: BoxDecoration(
                  color: Theme.of(context).colorScheme.primaryContainer,
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Icon(
                  _getCategoryIcon(expense.category),
                  color: Theme.of(context).colorScheme.onPrimaryContainer,
                  size: 20,
                ),
              ),
              const SizedBox(width: 12),
              // Main Content
              Expanded(
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    // Label takes full width
                    Text(
                      expense.label,
                      style: const TextStyle(
                        fontWeight: FontWeight.bold,
                        fontSize: 15,
                      ),
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                    ),
                    // Category below label
                    if (expense.category != null &&
                        expense.category!.isNotEmpty) ...[
                      const SizedBox(height: 4),
                      Container(
                        padding: const EdgeInsets.symmetric(
                          horizontal: 6,
                          vertical: 2,
                        ),
                        decoration: BoxDecoration(
                          color: Colors.grey[200],
                          borderRadius: BorderRadius.circular(4),
                        ),
                        child: Text(
                          expense.category!,
                          style: TextStyle(
                            fontSize: 10,
                            color: Colors.grey[700],
                          ),
                        ),
                      ),
                    ],
                    // Notes - only visible when searching
                    if (isSearching &&
                        expense.note != null &&
                        expense.note!.isNotEmpty) ...[
                      const SizedBox(height: 4),
                      Text(
                        expense.note!,
                        style: TextStyle(fontSize: 11, color: Colors.grey[600]),
                        maxLines: 3,
                        overflow: TextOverflow.ellipsis,
                      ),
                    ],
                  ],
                ),
              ),
              const SizedBox(width: 8),
              // Price and +/- when in event mode
              Row(
                mainAxisSize: MainAxisSize.min,
                children: [
                  if (eventAssignmentMode) ...[
                    IconButton(
                      icon: Icon(
                        Icons.remove_circle_outline,
                        size: 22,
                        color: isInEvent ? Colors.red : Colors.grey,
                      ),
                      onPressed: isInEvent ? onRemoveFromEvent : null,
                      padding: EdgeInsets.zero,
                      constraints: const BoxConstraints(
                        minWidth: 32,
                        minHeight: 32,
                      ),
                    ),
                    const SizedBox(width: 4),
                  ],
                  Text(
                    '₹${expense.price.toStringAsFixed(0)}',
                    style: TextStyle(
                      fontSize: 16,
                      fontWeight: FontWeight.bold,
                      color: Theme.of(context).colorScheme.primary,
                    ),
                  ),
                  if (eventAssignmentMode) ...[
                    const SizedBox(width: 4),
                    IconButton(
                      icon: Icon(
                        Icons.add_circle_outline,
                        size: 22,
                        color: !isInEvent ? Colors.green : Colors.grey,
                      ),
                      onPressed: !isInEvent ? onAddToEvent : null,
                      padding: EdgeInsets.zero,
                      constraints: const BoxConstraints(
                        minWidth: 32,
                        minHeight: 32,
                      ),
                    ),
                  ],
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }

  IconData _getCategoryIcon(String? category) {
    switch (category) {
      case 'Food & Groceries':
        return Icons.restaurant;
      case 'Transportation':
        return Icons.directions_car;
      case 'Utilities':
        return Icons.bolt;
      case 'Shopping':
        return Icons.shopping_bag;
      case 'Entertainment':
        return Icons.movie;
      case 'Healthcare':
        return Icons.medical_services;
      case 'Education':
        return Icons.school;
      case 'Bills & Payments':
        return Icons.receipt;
      case 'Personal Care':
        return Icons.spa;
      case 'Home & Maintenance':
        return Icons.home_repair_service;
      case 'Travel':
        return Icons.flight;
      case 'Gifts & Donations':
        return Icons.card_giftcard;
      default:
        return Icons.category;
    }
  }
}
